import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const dbSchema = appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'symptom_logs',
      columns: [
        { name: 'log_date', type: 'string' },
        { name: 'cycle_day', type: 'number', isOptional: true },
        { name: 'cycle_phase', type: 'string', isOptional: true },
        { name: 'drsp_scores', type: 'string' },
        { name: 'physical_symptoms', type: 'string' },
        { name: 'adhd_ef_scores', type: 'string', isOptional: true },
        { name: 'adhd_med_effectiveness', type: 'number', isOptional: true },
        { name: 'sleep_quality', type: 'number', isOptional: true },
        { name: 'sleep_hours', type: 'number', isOptional: true },
        { name: 'energy_level', type: 'number', isOptional: true },
        { name: 'functional_impairment', type: 'string', isOptional: true },
        { name: 'spotting', type: 'boolean' },
        { name: 'fast_log', type: 'boolean' },
        { name: 'crisis_flag', type: 'boolean' },
        { name: 'bad_day_only', type: 'boolean' },
        { name: 'free_text_note', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'server_id', type: 'string', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'pcos_lab_values',
      columns: [
        { name: 'test_date', type: 'string' },
        { name: 'lab_type', type: 'string' },
        { name: 'value', type: 'number' },
        { name: 'unit', type: 'string' },
        { name: 'reference_low', type: 'number', isOptional: true },
        { name: 'reference_high', type: 'number', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'server_id', type: 'string', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'peri_hot_flashes',
      columns: [
        { name: 'occurred_at', type: 'number' },
        { name: 'severity', type: 'number', isOptional: true },
        { name: 'duration_minutes', type: 'number', isOptional: true },
        { name: 'flash_type', type: 'string', isOptional: true },
        { name: 'sleep_disrupted', type: 'boolean' },
        { name: 'sheet_change', type: 'boolean' },
        { name: 'trigger', type: 'string', isOptional: true },
        { name: 'accompanying', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'server_id', type: 'string', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'safety_plans',
      columns: [
        { name: 'created_in_phase', type: 'string', isOptional: true },
        { name: 'warning_signs', type: 'string' },
        { name: 'coping_strategies', type: 'string' },
        { name: 'contacts', type: 'string' },
        { name: 'reasons_to_live', type: 'string' },
        { name: 'crisis_numbers', type: 'string' },
        { name: 'locked_at', type: 'number', isOptional: true },
        { name: 'last_updated', type: 'number' },
        { name: 'server_id', type: 'string', isOptional: true },
      ],
    }),
  ],
});
