project_id = "your-project-id"

[api]
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
site_url = "http://localhost:8081"
additional_redirect_urls = ["hormonaiq://reset-password"]
jwt_expiry = 3600
enable_signup = true
